### ISSUE TITLE
[description] #2 

### ISSUE THREAD

**Issue by kairav** [SoftwareEngineeringToolDemos/ICSE-2011-UMLsec#2]
Project description is not filled in.

**Comment by RimiChen** [comment]
If your are saying about the description under the title,it was filled. And I am pretty sure that I filled the part when created this repo.

So, what do you mean about the project description? Could you give more detail information about that, then I (or you fix it by pull request) can fix it.

**Comment by kairav** [comment]
I was checking the description at the wrong place. Closing the issue
